plugins:
  - jest

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {'import/extensions': 'off', "class-methods-use-this": "off", "import/no-cycle": "off", "import/no-named-as-default-member":"off", "no-restricted-syntax":"off" }
